### ISSUE TITLE
2.10 Release Plan

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#1195]
Issue so we can decide which features we would like to see in the `2.9` release. This is not an exhaustive list, but we should list here only issues that would **block** the release. If some other features end up going into `2.9` the better, but they not need to be listed here.

- [x] Move py.code to pytest.code (#103): this will make it easier to fix a number of lingering bugs (which can then be done in later big-fix releases like 2.9.1, 2.9.2, etc);
- [ ] re-enable all warnings by default (#1191)
- [ ] Option to treat warnings as errors (#1173)

(This is my personal initial take on the subject, feel disagree with me)

Also, if we have a venue more appropriate to discuss this, feel free to suggest it.

cc @RonnyPfannschmidt @hpk42 @flub @The-Compiler @bubenkoff (feel free to cc anyone else I forgot)

**Comment by hpk42** [comment]
i agree the move of py.code to pytest.code would be good even though it's not strictly neccessary.  Can't remember the details of what is involved with respect to the moving and so not sure how much work it is. 

in any case i don't have any issues of my own currently that need to be part of pytest-2.9.  It'd be fine to release pytest-2.9 pretty soon and head for a 2.10 or 3.0 for the moved pytest.code as well.

**Comment by The-Compiler** [comment]
Since we agreed we want a 2.9 out rather sooner than later, is it okay if I move this and all issues with a 2.9 milestone to 2.10?

**Comment by nicoddemus** [comment]
Sure, thanks!

Em qui, 25 de fev de 2016 17:32, Florian Bruhin <notifications@github.com>
escreveu:

**Comment by The-Compiler** [comment]
Reopening as I moved it to 2.10

**Comment by The-Compiler** [comment]
I'm guessing we can close this now with the 3.0 plans?

**Comment by nicoddemus** [comment]
Sure! Closing.
