### ISSUE TITLE
No tengo plicsionea de raíz todo es vi web y denderizado

### ISSUE THREAD

**Issue by Thedoctor1989** [pytest-dev/pytest#12620]
- [ ] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

**Comment by nicoddemus** [comment]
Sorry @Thedoctor1989 can you write in English please? (I tried using google translator but it did not turn out anything useful).
