### ISSUE TITLE
Remaining issues for pytest 6

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#7528]
From https://github.com/pytest-dev/pytest/pull/7362#issuecomment-662201013 by @nicoddemus:

> I believe this is the last PR required for 6.0. 👍

I think there are some more things to be done first. Here's a checklist from the top of my head:

- [x] #7362 ("Change pytest deprecation warnings into errors for 6.0 release") obviously
- [x] #7503 ("pytest 6: Make --strict imply --strict-config?") - should be a rather easy change and I'd rather do this now instead of changing the behavior again in pytest 7
- [x] Decide what to do about #7495 ("6.0.0rc1 pytest.skip mypy error: Attribute function "__call__" ... does not accept self argument")
- [ ] Maybe wait a bit more until @hroncok looked at the test failures in Fedora? See https://github.com/pytest-dev/pytest/issues/7517#issuecomment-661269706 and https://src.fedoraproject.org/rpms/pytest/pull-request/17#comment-50314 - if I'm reading this right, only 5 packages still need a look at their build log.

Also see the [6.0 milestone](https://github.com/pytest-dev/pytest/milestone/24), I took the freedom to add the issues I mentioned above.

**Comment by hroncok** [comment]
> if I'm reading this right, only 5 packages still need a look at their build log.

Yes. It was very tedious, so I've taken a break. Will try to continue soon.

**Comment by nicoddemus** [comment]
Thanks for putting up this list @The-Compiler. 👍

**Comment by nicoddemus** [comment]
Took the liberty of going ahead and creating https://github.com/pytest-dev/pytest/issues/7532 to track the fedora packages, assigning it to @hroncok.

I'm closing this parent issue as I think each individual issue has been tracked/resolved now.

Thanks again @The-Compiler for compiling this list! 👍
